version: "3.8"

services:
  docker-registry:
    image: registry:2
    volumes:
      - docker-registry-vol:/var/lib/registry
    networks:
      - swarmpit_net
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    #      - REGISTRY_AUTH=htpasswd
    #      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
    #      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    #    secrets:
    #      - source: registry-auth
    #        target: /auth/htpasswd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 512M
    ports:
      - "5000:5000"

networks:
  swarmpit_net:
    external: true

volumes:
  docker-registry-vol:
