version: "3.8"

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    volumes:
      - docker-registry-vol:/var/lib/registry # Persistent storage for images
    networks:
      - docker-registry-nw
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager] # Ensures registry runs on a manager node
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: docker-registry-ui
    networks:
      - docker-registry-nw
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  docker-registry-nw:
    driver: overlay
    attachable: true

volumes:
  docker-registry-vol:
    driver: local
