version: "3.8"

services:
  docker-registry:
    image: registry:2
    volumes:
      - docker-registry-vol:/var/lib/registry
    networks:
      - swarmpit_net
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    #      - REGISTRY_AUTH=htpasswd
    #      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
    #      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    #    secrets:
    #      - source: registry-auth
    #        target: /auth/htpasswd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 512M
    ports:
      - "5000:5000"

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    networks:
      - docker-registry-nw
    ports:
      - "8002:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  swarmpit_net:
    external: true
  docker-registry-nw:
    driver: overlay
    attachable: true

volumes:
  docker-registry-vol:
