version: "3.9"
services:
  docker-registry:
    image: registry:2
    volumes:
      - docker-registry-vol:/var/run/docker.sock
    networks:
      - docker-registry-nw
    ports:
      - 5000:5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    networks:
      - docker-registry-nw
    ports:
      - "8002:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  docker-registry-nw:
    driver: overlay
    attachable: true

volumes:
  docker-registry-vol:
